# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6322b786fad64aacfed9767fae6443171c53fd79d96ffd88175031f4de607fcbf2551d004a3807cdc6c490a0f3c53677ad46cf9d9321ffc080a6d1039995d1d

test:
  secret_key_base: 49ba5a3c3e1ca02367465e7c20297563c76b6b02d225aa99dc40f8c8c828c8e7a584b1c564ffd10626471c9d463482b07b7cedae00e8eee538ebce5dd2b531cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
